version: '3'
services:
  joomla:
    #image: joomla:3.6.2-apache-php7
    image: joomla:3.6.2-apache
    links:
     - mysql
    ports:
     - "80:80"
    environment:
     - JOOMLA_DB_NAME=goldenmi_data
     - JOOMLA_DB_HOST=mysql:3306
     - JOOMLA_DB_PASSWORD=12345678
    volumes:
     - ./www:/var/www/html
    depends_on:
     - mysql
  
  mysql:
    image: mysql:5.7.14
    environment:
     - MYSQL_ROOT_PASSWORD=12345678
     - MYSQL_DATABASE=goldenmi_data
    volumes:
     - ./database:/var/lib/mysql
     - ./goldenmi.sql:/docker-entrypoint-initdb.d/goldenmi_data.sql:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.6.4-1
    links:
     - mysql
    ports:
     - "81:80"
    environment:
     - PMA_HOST=mysql
